add nextcord-sql
sparkedhost/preinstalls pull request #11
Opened 2023-02-15 15:54 UTC by Jpuf0

this resolved issue #8 

please do let me know of any changes.

2023-02-15 19:01 UTC, BetTD requested changes
Thanks a lot for your contribution! If you could make the requested changes and also include a README file that explains how to set this up, that would be awesome.

2023-02-15 19:01 UTC, BetTD commented on python/discord-bots/nextcord-sql/index.py
> +TESTING_GUILD_ID = 1234567890 # change to example
Move this to .env

2023-02-15 19:01 UTC, BetTD commented on python/discord-bots/nextcord-sql/index.py
> +        database="nextcord",
Move this to .env as well

2023-02-15 19:05 UTC, BetTD commented on python/discord-bots/nextcord-sql/index.py
> +        database="nextcord",
Also rename the folder from `nextcord-sql` to `nextcord-mysql`, as this implementation is specific to MySQL/MariaDB and would probably require further changes for it to work with other SQL database software (e.g. PostgreSQL), for which we don't provide database servers.

2023-02-15 19:23 UTC, hwalker928 commented on python/discord-bots/nextcord-sql/requirements.txt
> +python-dotenv
Shouldn't asyncmy be part of this?

2023-02-18 13:26 UTC, Jpuf0 commented
should be resolved in the latest commit

2023-03-01 14:50 UTC, merged